build:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: ['']
    script:
        - mkdir -p /kaniko/.docker
        - cp -f $CI_PROJECT_DIR/Dockerfiles/Application/* $CI_PROJECT_DIR
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/$CI_REGISTRY_PATH/deep-lynx:$CI_PIPELINE_IID
        - cd "$CI_PROJECT_DIR/Admin Web App"
        - cp -f $DEEPLYNX_ADMIN_UI_CONFIG_DEV "$CI_PROJECT_DIR/Admin Web App/.env"
        - /kaniko/executor --context "$CI_PROJECT_DIR/Admin Web App" --dockerfile "$CI_PROJECT_DIR/Admin Web App/Dockerfile" --destination $CI_REGISTRY/$CI_REGISTRY_PATH/deep-lynx-admin-dev:$CI_PIPELINE_IID
        - cp -f $DEEPLYNX_ADMIN_UI_CONFIG_PROD "$CI_PROJECT_DIR/Admin Web App/.env"
        - /kaniko/executor --context "$CI_PROJECT_DIR/Admin Web App" --dockerfile "$CI_PROJECT_DIR/Admin Web App/Dockerfile" --destination $CI_REGISTRY/$CI_REGISTRY_PATH/deep-lynx-admin-prod:$CI_PIPELINE_IID
    only:
        - master
deploy_development:
    stage: deploy
    image: mcr.microsoft.com/azure-cli:latest
    script:
        - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        - mkdir -p $HOME/.kube
        - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
        - kubectl apply -f $DEEPLYNX_DEV_KUBERNETES
    environment:
        name: development
    only:
        - master
deploy_production:
    stage: deploy
    image: mcr.microsoft.com/azure-cli:latest
    script:
        - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        - mkdir -p $HOME/.kube
        - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
        - kubectl apply -f $DEEPLYNX_DEV_KUBERNETES
    environment:
        name: production
    when: manual
    only:
        - master
