build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh $BUILD
  only:
    - master
deploy_development:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  script:
    - sh $DEPLOY_DEV
  environment:
    name: development
  only:
    - master
deploy_production:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  script:
    - sh $DEPLOY_PROD
  environment:
    name: production
  when: manual
  only:
    - master